project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/selked/selked.github.io
  repo-actions: [source]
  title: "Daulton Selke's Scholarly Website"
  navbar:
    pinned: true
    right:
      - href: index.qmd
        icon: house
        text: Home
      - icon: tools
        text: Resources
        menu:
          - text: R Workbook for Undergrad Research Methods
            href: https://selked.github.io/SOC300-Intro-R
            icon: book
          - text: R Package for Batch Audio Transcription
            href: https://github.com/selked/scrivenR
            icon: github
      - href: posts.qmd
        icon: pencil-square
        text: Blog
      
        
      
    
      
format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true

editor: visual

